name: Delivery

on:
  push:
    branches:
      - master

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: us.gcr.io/${{ secrets.GCP_PROJECT }}/sampleflask:${{ github.sha }}

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: GCP Authenticate
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build a docker image
        run: |
          docker build \
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} \
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --build-arg DB_HOST=${{ secrets.DB_HOST }} \
            --build-arg DB_NAME=${{ secrets.DB_NAME }} \
            -t $IMAGE .
      - name: Push the docker image
        run: docker push $IMAGE
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy sampleflask \
            --image $IMAGE \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --platform managed \
            --quiet
